apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argotest
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: argotest
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
