apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argotest
spec:
  destination:
    name: ''
    namespace: argotest
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/grafana/deploy
    repoURL: 'https://github.com/ArgTang/hometest'
    targetRevision: HEAD
  project: argotest
  helm:
    version: v3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
