apiVersion: v1
kind: Secret
metadata:
  name: repo-hometest
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ArgTang/hometest
